export const listDataJenjang = [
  "Junior / Fresh Graduate",
  "Middle",
  "Senior",
  "Professional",
];

export const listDataFunction = [
  "Accounting and Tax",
  "Administration and Clerical",
  "Architecture and Constructio",
  "Audit and Risk Management",
  "Banking and Financial Services",
  "Communication",
  "Data and Statistics",
  "Development Program",
  "Education",
  "Engineering",
  "Enviroment, Health, and Safety",
  "Finance and Treasury",
  "General Affair",
  "Health and Medical",
  "Hospitality",
  "Human Capital",
  "Information Technology",
  "Legal",
  "Marketing",
  "Production and Manufacturing",
  "Sales",
  "Secretary and Personal Assisstance",
  "Security and Task Force",
  "Strategic Planning",
  "Supply Chain",
];
